services:
  web:
    container_name: personal-website
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3888:80"
    volumes:
      - /usr/share/nginx/html
    restart: always
    command: nginx -g 'daemon off;'